plugins {
    id 'java'
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.10"
}

group = "me.Tonus_"
version = "3.0.0-pre1"
var configVersion = "4"
var messageVersion = "3"


var prerelease = version.contains("pre") || version.contains("beta") || version.contains("alpha")

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16

    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

idea {
    module {
        excludeDirs = [
                file(".gradle"),
                file("build"),
                file("gradle"),
                file("gradlew"),
                file("gradlew.bat")
        ]
    }
}

sourceSets {
    main {
        java.srcDirs = ["src/main/java"]
        resources.srcDirs = ["src/main/resources/"]
    }
    test {
        java.srcDirs = ["src/test/java"]
        resources.srcDirs = ["src/test/resources/"]
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://repo.codemc.org/repository/maven-public/' }
    maven { url = "https://repo.aikar.co/content/groups/aikar/" }
    maven { url = "https://repo.papermc.io/repository/maven-public/" }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url = 'https://oss.sonatype.org/content/repositories/central' }
    mavenLocal()
}

dependencies {
    // Build
    implementation "org.bstats:bstats-bukkit:3.1.0"
    implementation "co.aikar:acf-paper:0.5.1-SNAPSHOT"
    implementation "org.reflections:reflections:0.10.2"
    compileOnly "org.jetbrains:annotations:26.0.2"
    compileOnly "org.yaml:snakeyaml:2.4"
    compileOnly "org.projectlombok:lombok:1.18.38"
    annotationProcessor "org.projectlombok:lombok:1.18.38"

    compileOnly "com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT"
    compileOnly "com.google.code.gson:gson:2.13.1" // CVE mitigation: spigot-api
    compileOnly "com.google.guava:guava:33.4.8-jre" // CVE mitigation: spigot-api
    compileOnly 'junit:junit:4.13.2' // CVE mitigation: spigot-api

    // Testing
    testImplementation platform("org.junit:junit-bom:5.13.1")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testImplementation "org.mockito:mockito-core:5.18.0"

    testImplementation "com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT"
    testImplementation "com.google.code.gson:gson:2.13.1"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }

    doFirst {
        def mockitoJar = configurations.testRuntimeClasspath.find {
            it.name.startsWith("mockito-core")
        }
        if (mockitoJar) jvmArgs "-javaagent:${mockitoJar}", "-Xshare:off"
    }
}

build.dependsOn shadowJar
shadowJar {
    relocate "org.bstats", "${project.group}.bstats"
    relocate "co.aikar.commands", "${project.group}.acf"
    relocate "co.aikar.locales", "${project.group}.locales"

    archiveFileName.set("${project.name}-${project.version}.jar")

    processResources {
        filesMatching("plugin.yml") {
            println "Expanding plugin.yml"
            expand(version: project.version)
        }

        filesMatching("config.yml") {
            println "Expanding config.yml"
            expand(hatcosmetics_config_version: configVersion)
        }

        filesMatching("messages.yml") {
            println "Expanding messages.yml"
            expand(hatcosmetics_config_version: messageVersion)
        }
    }

    manifest {
        attributes("Is-Prerelease": prerelease)
        attributes("Supported-Config-Version": configVersion)
        attributes("Supported-Message-Version": messageVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

// TODO: Remove temporary testing setup!
tasks.register("copyToTestServer", Sync) {
    dependsOn "build"
    mustRunAfter "build"

    def pluginsDir = "${project.projectDir}/test_server/plugins";

    doFirst {
        delete fileTree(pluginsDir) { include "**/*.jar" }
    }

    from(fileTree(layout.buildDirectory.dir("libs")) {
        include("*.jar")
    })
    into(pluginsDir)
}

// TODO: Remove temporary testing setup!
tasks.register("runOnTestServer", Exec) {
    dependsOn "copyToTestServer"
    mustRunAfter "copyToTestServer"

    workingDir "${project.layout.projectDirectory}/test_server/"
    commandLine "java", "-Xms1G", "-Xmx1G", "-Dpaper.log-level=WARN", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "paper-1.21.4-232.jar", "--nogui"
}
